source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mongo'
gem 'mongoid', '~> 4.0.0'
gem 'moped', '~> 2.0.0'
gem 'shotgun'
gem 'chartkick'
gem 'groupdate'
gem 'jenkins_api_client', '~> 1.0.0'
gem 'octokit', '~> 3.0'
gem 'pry'
gem 'rails'
gem 'bson', '~> 2.2'
gem 'mongodb'
gem 'bson_ext'
