sun_web_team:
  tag_project: 'Sun - Firefox Tests - Regression'
  tags:
    regression_tag: '@regression'
times_web_team:
  tag_project: 'Sun - Firefox Tests - Regression'
  tags:
    regression_tag: '@regression'
app_team:
  tag_project: 'iOS_7_Ipad_Regression_build_nightly'
  tags:
    ios: '@ios'
    android: '@android7'







